name: Build Docker 

on: workflow_dispatch

      

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@main

    - name: Build & Push Image

      run: |        

         echo "dockerHubSecret" | docker login -u urDockerName --password-stdin

         docker image build -t yourdockerImage .

         docker push yourdockerImage
